version: "3.9"
name: "openedx-external-db"
services:
  db:
    image: postgres
    ports:
      - 5433:5432
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
      - ./data/init/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=tIjh4N0G91GxHMmiFLC6er65O8O0wlBunE0W87HSjrWFqeOZPwj4numdWdyDyb304rskVaJfVkz3e7qeJUj4R1WZzR2ijdbrzDpS
    restart: unless-stopped
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - 3030:3030
    volumes:
      - ./app:/app
    restart: unless-stopped

